---
# tasks file for ansible-role-oiofs

- include: install.yaml

- include_tasks: mountpoint.yaml
  with_items: {{hostvars[inventory_hostname]['mountpoints']}}
  loop_control:
    loop_var: mountpoint
...
